// Teste local isolado: npm install --no-save --package-lock=false @electric-sql/pglite && node tests/database.mjs
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('app.user_id',true),'')::uuid$$;
grant usage on schema auth,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(bucket_id text,name text);alter table storage.objects enable row level security;
create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;
`);
await db.exec(readFileSync(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',p='33333333-3333-4333-8333-333333333333';
await db.exec(`insert into auth.users values('${a}'),('${b}');set role authenticated;set app.user_id='${a}';`);
await db.query(`insert into public.products(id,owner,name,category,data) values($1,$2,'Peça teste','Brincos',$3)`,[p,a,JSON.stringify({purchase:13.99,freight:0,quantity:1,packaging:1,overhead:0.5,fixedFee:0,fee:5,tax:0})]);
const scalar=async(sql,params=[])=>Object.values((await db.query(sql,params)).rows[0])[0];
assert.equal(await scalar('select public.adjust_stock($1,10,3,0)',[p]),true);
assert.equal(await scalar('select public.adjust_stock($1,20,3,0)',[p]),false);
const sale=()=>db.query(`select * from public.record_sale('test-sale-000000001',$1,2,4500,current_date)`,[p]);
const {rows:[s]}=await sale();assert.equal(Number(s.total),9000);assert.equal(Number(s.cost_total),3098);assert.equal(Number(s.fee_total),450);
assert.equal(await scalar('select stock from public.products'),8);
await sale();assert.equal(await scalar('select stock from public.products'),8);
await assert.rejects(db.query(`select * from public.record_sale('test-sale-000000001',$1,3,4500,current_date)`,[p]),/ID_CONFLICT/);
await assert.rejects(db.query(`select * from public.record_sale('test-sale-000000002',$1,9,4500,current_date)`,[p]),/INSUFFICIENT_STOCK/);
await assert.rejects(db.query('update public.products set stock=900 where id=$1',[p]),/permission denied/);
await assert.rejects(db.query('delete from public.sales'),/permission denied/);
await db.exec(`set app.user_id='${b}'`);assert.equal(await scalar('select count(*) from public.products'),0);assert.equal(await scalar('select count(*) from public.sales'),0);
assert.equal(await scalar('select public.adjust_stock($1,9,3,8)',[p]),false);
await assert.rejects(db.query(`select public.cancel_sale('test-sale-000000001')`),/NOT_FOUND/);
await db.exec(`set app.user_id='${a}'`);await db.exec(`select public.cancel_sale('test-sale-000000001');select public.cancel_sale('test-sale-000000001');`);
assert.equal(await scalar('select stock from public.products'),10);
assert.equal(await scalar('select cancelled from public.sales'),1);
await assert.rejects(db.query('delete from public.products where id=$1',[p]),/foreign key/);
await db.exec('set role anon');await assert.rejects(db.query('select * from public.products'),/permission denied/);
await assert.rejects(db.query('select public.adjust_stock($1,1,1,10)',[p]),/permission denied/);
await db.close();console.log('PASS: vendas, centavos, reenvio, saldo, cancelamento, RLS, permissões e histórico.');
