'use client';
import ProductFilters from '@/components/product-filters';
import {emptyProductFilters,filterProducts} from '@/lib/product-filters';
import Operations from './operations';
import {SKU_MAX_LENGTH} from '@/lib/sku';
import {useEffect,useState,type FormEvent} from 'react';
import {Gem,Calculator,Package,Plus,Camera,ArrowUpRight,Save,Trash2,Pencil,LockKeyhole,RotateCcw,Info,Boxes,ChartNoAxesCombined} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogTrigger,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {calculate,initial,money,keys,categories,type Values,type Product} from '@/lib/pricing';
function arithmetic(source:string){const tokens=source.replaceAll(',','.').replace(/\s/g,'').match(/\d*\.?\d+|[+\-*/()]/g)||[];if(tokens.join('')!==source.replaceAll(',','.').replace(/\s/g,'')||tokens.length>100)throw Error('Conta inválida');let i=0;function atom():number{if(tokens[i]==='-'){i++;return -atom();}if(tokens[i]==='+'){i++;return atom();}if(tokens[i]==='('){i++;const v=sum();if(tokens[i++]!==')')throw Error('Feche os parênteses');return v;}const token=tokens[i++];if(!token||!/^\d*\.?\d+$/.test(token))throw Error('Complete a conta');return Number(token);}function mult(){let v=atom();while(['*','/'].includes(tokens[i])){const op=tokens[i++],b=atom();v=op==='*'?v*b:v/b;}return v;}function sum(){let v=mult();while(['+','-'].includes(tokens[i])){const op=tokens[i++],b=mult();v=op==='+'?v+b:v-b;}return v;}const result=sum();if(i!==tokens.length||!Number.isFinite(result))throw Error('Conta inválida ou divisão por zero');return result;}
export default function Home(){
 const [tab,setTab]=useState('calculator'),[values,setValues]=useState<Values>({...initial}),[name,setName]=useState(''),[sku,setSku]=useState(''),[category,setCategory]=useState('Brincos'),[editing,setEditing]=useState<string|null>(null),[photo,setPhoto]=useState<string|null>(null),[file,setFile]=useState<File|null>(null),[removed,setRemoved]=useState(false),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState<Product|null>(null),[deleteBusy,setDeleteBusy]=useState(false),[expression,setExpression]=useState(''),[answer,setAnswer]=useState('0');
 const [filters,setFilters]=useState({...emptyProductFilters});
 const filteredProducts=filterProducts(products,filters);
 const result=calculate(values);
 const original=products.find(p=>p.id===editing);
 const dirty=name!==(original?.name??'')||sku!==(original?.sku??'')||category!==(original?.category??'Brincos')||keys.some(k=>values[k]!== (original?.[k]??initial[k]))||!!file||removed;
 const [discardAction,setDiscardAction]=useState<(()=>void)|null>(null);
 const lowStock=products.filter(p=>p.stock<=p.stock_min).length;
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function protectDraft(action:()=>void){if(dirty)setDiscardAction(()=>action);else action();}
 function reset(){protectDraft(clearForm);}
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/products');const data=await r.json() as Product[] & {error?:string};if(!r.ok)throw Error(data.error);setProducts(data);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar os produtos.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(!file)return;const url=URL.createObjectURL(file);setPhoto(url);return()=>URL.revokeObjectURL(url);},[file]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'calculate_product_price',title:'Calcular preço da peça',description:'Atualiza os custos na calculadora e retorna preço, custo e lucro; não salva um produto.',inputSchema:{type:'object',properties:Object.fromEntries(keys.map(k=>[k,{type:'number',minimum:0}])),additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Informe os custos');const incoming=input as Record<string,unknown>;if(Object.keys(incoming).some(k=>!keys.includes(k as typeof keys[number])))throw Error('Campo inválido');const next={...initial,...incoming} as Values;if(!calculate(next).valid)throw Error('Valores ou porcentagens inválidos');setValues(next);setTab('calculator');return calculate(next);}},{signal:controller.signal})).catch(e=>{if(!controller.signal.aborted)console.error(e);});}catch(e){console.error(e);}return()=>controller.abort();},[]);
 function clearForm(){setEditing(null);setName('');setSku('');setCategory('Brincos');setValues({...initial});setFile(null);setPhoto(null);setRemoved(false);setTab('calculator');}
 function edit(p:Product){protectDraft(()=>openProduct(p));}
 function openProduct(p:Product){setEditing(p.id);setName(p.name);setSku(p.sku??'');setCategory(p.category);setValues(Object.fromEntries(keys.map(k=>[k,p[k]])) as Values);setFile(null);setPhoto(p.photo);setRemoved(false);setTab('calculator');window.scrollTo({top:0,behavior:'smooth'});}
 async function save(event:FormEvent){event.preventDefault();if(saving||!result.valid)return;setSaving(true);try{const data=new FormData();data.set('data',JSON.stringify({...values,name,sku,category,id:editing,removePhoto:removed}));if(file)data.set('photo',file);const r=await fetch('/api/products',{method:'POST',body:data}),p=await r.json() as Product & {error?:string};if(!r.ok)throw Error(p.error);setProducts(old=>[p,...old.filter(x=>x.id!==p.id)]);setEditing(p.id);setName(p.name);setSku(p.sku??'');setFile(null);setPhoto(p.photo);setRemoved(false);setError('');toast.success('Produto salvo com sucesso.');}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível salvar. Seus dados continuam aqui.');}finally{setSaving(false);}}
 async function remove(){if(!deleting)return;setDeleteBusy(true);try{const r=await fetch('/api/products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:deleting.id})});if(!r.ok)throw Error((await r.json() as {error:string}).error);setProducts(old=>old.filter(p=>p.id!==deleting.id));if(editing===deleting.id)clearForm();setDeleting(null);toast.success('Produto excluído.');}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível excluir.');}finally{setDeleteBusy(false);}}
 function numberField(key: keyof Values,label:string,unit='R$',hint?:string){return <label className="field" htmlFor={key}><span>{label}</span><div className="input-wrap"><span>{unit}</span><input id={key} type="number" min={key==='quantity'?1:0} aria-describedby={hint?`${key}-hint`:undefined} max={unit==='%'?'99.99':undefined} step={key==='quantity'?'1':'0.01'} inputMode={key==='quantity'?'numeric':'decimal'} value={values[key]===0?'':values[key]} placeholder="0,00" onChange={e=>setValues(v=>({...v,[key]:e.target.value===''?0:Number(e.target.value)}))}/></div>{hint&&<small id={`${key}-hint`}>{hint}</small>}</label>;}
 return <><a className="skip-link" href="#main-content">Ir para o conteúdo</a><Toaster theme="light" richColors/><header className="topbar"><div className="brand"><span className="brand-icon"><Gem size={25}/></span><div><b>by carolla<span>®</span></b><small>ATELIÊ DE PREÇOS</small></div></div><span className="private"><LockKeyhole size={14}/> Seu espaço privado</span><form action="/auth/logout" method="post"><button className="outline" type="submit">Sair</button></form></header><main id="main-content" className="atelier-main">
 <div className="heading"><div><p className="eyebrow">GESTÃO DA SUA LOJA</p><h1>Seu ateliê, em dia<span className="title-dot">.</span></h1><p>Mais clareza nos preços. Mais cuidado com o seu negócio.</p></div><Dialog><DialogTrigger asChild><button className="outline"><Calculator size={17}/> Conta rápida</button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Conta rápida</DialogTitle><DialogDescription>Some, subtraia, multiplique (*) ou divida (/). Use parênteses se precisar.</DialogDescription></DialogHeader><input className="plain-input" aria-label="Conta" value={expression} onChange={e=>setExpression(e.target.value)} placeholder="Ex.: (120 + 30) / 10"/><output className="quick-answer">{answer}</output><button className="primary" onClick={()=>{try{setAnswer(arithmetic(expression).toLocaleString('pt-BR',{maximumFractionDigits:8}));}catch(e){setAnswer((e as Error).message);}}}>Calcular</button></DialogContent></Dialog></div>
 <section className="overview-strip" aria-label="Visão geral do ateliê"><div><Package size={18} aria-hidden="true"/><span>Produtos cadastrados<strong>{loading?'—':products.length}</strong></span></div><div><Boxes size={18} aria-hidden="true"/><span>Peças em estoque<strong>{loading?'—':products.reduce((n,p)=>n+p.stock,0)}</strong></span></div><button type="button" onClick={()=>setTab('stock')} className={lowStock>0?'needs-attention':''}><span className="overview-indicator"/><span>Produtos para repor<strong>{loading?'—':lowStock}</strong></span><ArrowUpRight size={17} aria-hidden="true"/></button></section><Tabs value={tab} onValueChange={setTab}><div className="navline"><TabsList className="app-tabs" aria-label="Áreas do ateliê"><TabsTrigger value="calculator"><Calculator size={18} aria-hidden="true"/><span>Precificar</span></TabsTrigger><TabsTrigger value="products"><Package size={18} aria-hidden="true"/><span>Produtos</span> <span className="count">{products.length}</span></TabsTrigger><TabsTrigger value="stock"><Boxes size={18} aria-hidden="true"/><span>Estoque</span></TabsTrigger><TabsTrigger value="sales"><ChartNoAxesCombined size={18} aria-hidden="true"/><span>Vendas</span></TabsTrigger></TabsList><span className="nav-note">Valores em reais (R$)</span></div>
 <TabsContent value="calculator"><div className="workspace-heading"><div><p className="eyebrow">PRECIFICAÇÃO</p><h2>{editing?'Ajuste sua peça':'Encontre o preço da sua peça'}</h2><p>Preencha os custos e acompanhe o resultado ao lado.</p></div><span className={dirty?'draft-status pending':'draft-status'}>{dirty?'Alterações não salvas':editing?'Produto salvo':'Novo produto'}</span></div><form id="product-form" onSubmit={save} className="workspace"><div className="form-column">
 <section className="panel"><div className="section-heading"><span className="step">01</span><h2>{editing?'Editar produto':'Sua peça'}</h2>{editing&&<button className="text-button" type="button" onClick={reset}><Plus size={16}/> Nova peça</button>}</div><div className="identity-grid"><div className="upload-block"><label className={'upload '+(photo?'has-photo':'')} htmlFor="photo">{photo?<img src={photo} alt="Foto da peça"/>:<><Camera size={25}/><strong>Adicionar foto</strong><small>JPG, PNG ou WebP</small><small>Até 3 MB</small></>}<input id="photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>3*1024*1024){toast.error('Use JPG, PNG ou WebP de até 3 MB.');e.target.value='';return;}setFile(f);setRemoved(false);}}/>{photo&&<span className="change-photo"><Camera size={14}/> Trocar foto</span>}</label>{photo&&<button type="button" className="remove-photo" onClick={()=>{setFile(null);setPhoto(null);setRemoved(true);}}>Remover foto</button>}</div><div className="identity-fields"><label className="field">Nome do produto <span className="required-hint">Obrigatório</span><input className="plain-input" required maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Brinco argola dourada"/></label><label className="field" htmlFor="sku">SKU (opcional)<input id="sku" className="plain-input" type="text" maxLength={SKU_MAX_LENGTH} value={sku} onChange={e=>setSku(e.target.value)} placeholder="Ex.: BR-001" autoComplete="off" spellCheck={false} aria-describedby="sku-hint"/><small id="sku-hint">Código único da peça na sua conta. Ex.: BR-001.</small></label><div className="field"><label htmlFor="category">Categoria</label><Select value={category} onValueChange={setCategory}><SelectTrigger id="category" className="category-select"><SelectValue/></SelectTrigger><SelectContent>{categories.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div></div></div></section>
 <section className="panel"><div className="section-heading"><span className="step">02</span><h2>Quanto custa a peça?</h2><span className="subtle">Por unidade</span></div><div className="fields-grid">{numberField('purchase','Compra da peça')}{numberField('packaging','Embalagem')}{numberField('freight','Frete da compra','R$','Valor total do frete do pedido.')}{numberField('quantity','Peças no pedido','un.','Divide o frete igualmente entre as peças.')}{numberField('overhead','Outros custos por peça','R$','Inclua mão de obra e despesas rateadas.')}{numberField('fixedFee','Tarifa fixa por venda','R$','Parcela atribuída a esta peça.')}</div><div className="cost-total"><span>Custo total por peça</span><strong>{Number.isFinite(result.cost)?money(result.cost):'—'}</strong></div></section>
 <section className="panel"><div className="section-heading"><span className="step">03</span><h2>Taxas e margem</h2></div><div className="fields-grid">{numberField('fee','Taxas de venda','%','Cartão, comissão ou marketplace.')}{numberField('tax','Impostos sobre a venda','%','Informe a alíquota aplicável à sua loja.')}{numberField('margin','Margem desejada','%','Percentual do preço final. Ajuste para sua meta.')}{numberField('sale','Seu preço de venda','R$','Opcional. Vazio usa o preço sugerido.')}</div></section>
 </div><aside className="result-column"><section className="price-panel"><div className="price-top"><span>SEU PREÇO DE VENDA</span><Gem size={23}/></div><p className="price-label">Preço sugerido por peça</p><output className="big-price" aria-live="polite">{result.valid?money(result.suggested):'—'}</output><div className="margin-pill">Margem desejada de {values.margin.toLocaleString('pt-BR')}%</div><div className="price-divider"/><div className="price-row"><span>Custo total</span><b>{Number.isFinite(result.cost)?money(result.cost):'—'}</b></div><div className="price-row"><span>Taxas e impostos</span><b>{result.valid?money(result.fees):'—'}</b></div><div className="price-row profit"><span>Lucro estimado por peça</span><b>{result.valid?money(result.profit):'—'}</b></div><p className="result-footnote">{values.sale>0?'Resultado considerando seu preço de '+money(values.sale)+'.':'Resultado considerando o preço sugerido.'}</p></section>
 <section className="panel breakdown"><div className="section-heading"><h2>Por dentro do preço</h2><ArrowUpRight size={18}/></div>{result.valid&&result.price>0?<><div className="bar"><span style={{width:`${Math.min(result.cost/result.price*100,100)}%`}}/><span style={{width:`${Math.min(result.fees/result.price*100,100)}%`}}/><span style={{width:`${Math.max(result.actualMargin,0)}%`}}/></div><div className="legend"><span><i/>Custos</span><span><i/>Taxas</span><span><i/>Lucro</span></div><div className="stat-row"><span>Margem neste preço</span><strong className={result.actualMargin<values.margin?'warning-text':''}>{result.actualMargin.toLocaleString('pt-BR',{maximumFractionDigits:1})}%</strong></div><div className="stat-row"><span>Preço sem lucro</span><strong>{money(result.minimum)}</strong></div></>:<p className="muted">Preencha o custo da peça para visualizar a composição.</p>}<p className="formula"><Info size={15}/> Preço = custo ÷ (1 − taxas − impostos − margem). Percentuais convertidos em decimais.</p></section>
 {!result.valid&&<div className="validation" role="alert">Use valores positivos, ao menos 1 peça no pedido e taxas + impostos + margem abaixo de 100%.</div>}{result.valid&&values.sale>0&&result.actualMargin+0.01<values.margin&&<div className="validation">{result.profit<0?'Esse preço gera prejuízo.':'Seu preço está abaixo da margem desejada.'}</div>}
 <div className="save-dock"><div className="mobile-price"><span>Preço sugerido</span><strong>{result.valid?money(result.suggested):'Revise os valores'}</strong></div><button className="primary save-button" disabled={saving||!result.valid} type="submit"><Save size={18}/>{saving?'Salvando…':editing?'Salvar alterações':'Salvar produto'}</button></div><button className="reset-button" type="button" onClick={reset}><RotateCcw size={14}/> Limpar para uma nova peça</button><p className="save-note"><LockKeyhole size={13}/>{dirty?'Salve para guardar suas alterações.':'Produtos e fotos privados na sua conta.'}</p><p className="estimate-note">O lucro é uma estimativa baseada nos custos informados. Inclua todas as despesas para evitar um preço insuficiente.</p></aside></form></TabsContent>
 <TabsContent value="products"><div className="products-heading"><div><h2>Suas peças, organizadas.</h2><p>{products.length} {products.length===1?'produto cadastrado':'produtos cadastrados'}</p></div><button className="primary" onClick={reset}><Plus size={17}/> Novo produto</button></div>{!loading&&!error&&products.length>0&&<ProductFilters value={filters} onChange={setFilters} count={filteredProducts.length} total={products.length}/>} {loading?<p className="loading" role="status">Carregando seus produtos…</p>:error?<div className="error-box" role="alert"><p>{error}</p><button className="outline" onClick={load}>Tentar novamente</button></div>:products.length===0?<Empty className="empty-products"><EmptyHeader><Package size={36}/><EmptyTitle>O primeiro produto começa aqui.</EmptyTitle><EmptyDescription>Cadastre uma peça com seus custos e foto. Ela ficará salva para consultar ou ajustar depois.</EmptyDescription></EmptyHeader><button className="primary" onClick={reset}><Plus size={17}/> Precificar minha primeira peça</button></Empty>:filteredProducts.length===0?<Empty><EmptyHeader><EmptyTitle>Nenhuma peça encontrada</EmptyTitle><EmptyDescription>Altere a busca ou limpe os filtros para ver mais produtos.</EmptyDescription></EmptyHeader><button className="outline" onClick={()=>setFilters({...emptyProductFilters})}>Limpar filtros</button></Empty>:<div className="product-grid" aria-label="Lista de produtos">{filteredProducts.map(p=>{const r=calculate(p);return <article className="product-card" key={p.id}><div className="product-image">{p.photo?<img src={p.photo} alt={p.name}/>:<><Gem size={42}/><span>Sem foto</span></>}<span className="category-tag">{p.category}</span></div><div className="product-body"><h3>{p.name}</h3>{p.sku&&<p className="product-sku">SKU: {p.sku}</p>}<span className={"stock-chip "+(p.stock<=p.stock_min?"low":"")}>{p.stock===0?'Sem estoque':`${p.stock} em estoque`}{p.stock>0&&p.stock<=p.stock_min?' · Repor':''}</span><div className="product-price"><strong>{money(r.price)}</strong><span>por peça</span></div><div className="product-numbers"><span>Custo <b>{money(r.cost)}</b></span><span>Lucro estimado <b className={r.profit<0?'warning-text':''}>{money(r.profit)}</b></span></div><div className="card-actions"><button className="outline" onClick={()=>edit(p)}><Pencil size={15}/> Editar peça</button><button className="icon-button danger-button" aria-label={`Excluir ${p.name}`} onClick={()=>setDeleting(p)}><Trash2 size={17}/></button></div></div></article>;})}</div>}</TabsContent><TabsContent value="stock"><Operations mode="stock" products={products} loading={loading} error={error} reload={load}/></TabsContent><TabsContent value="sales"><Operations mode="sales" products={products} loading={loading} error={error} reload={load}/></TabsContent></Tabs>
 <footer><span>by carolla <span className="footer-dot">·</span> Ateliê de Preços</span><span>Feito para cuidar de cada detalhe.</span></footer></main>
 <AlertDialog open={!!deleting} onOpenChange={o=>{if(!o&&!deleteBusy)setDeleting(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir esta peça?</AlertDialogTitle><AlertDialogDescription>O produto “{deleting?.name}”, seus custos e sua foto serão removidos. Essa ação não pode ser desfeita.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={deleteBusy}>Cancelar</AlertDialogCancel><AlertDialogAction className="destructive-action" disabled={deleteBusy} onClick={e=>{e.preventDefault();remove();}}>{deleteBusy?'Excluindo…':'Excluir produto'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><AlertDialog open={!!discardAction} onOpenChange={open=>{if(!open)setDiscardAction(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Descartar as alterações?</AlertDialogTitle><AlertDialogDescription>Você tem alterações nesta peça que ainda não foram salvas. Volte para salvar ou descarte para continuar.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Continuar editando</AlertDialogCancel><AlertDialogAction className="destructive-action" onClick={()=>{discardAction?.();setDiscardAction(null);}}>Descartar alterações</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
