'use client';
import ProductFilters from '@/components/product-filters';
import {emptyProductFilters,filterProducts} from '@/lib/product-filters';
import {useEffect,useState,type FormEvent} from 'react';
import {Plus,Download,Package,ShoppingBag,RefreshCw,Pencil,RotateCcw} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {toast} from 'sonner';
import {calculate,money,type Product} from '@/lib/pricing';
import {today,summarize,type Sale} from '@/lib/sales';
const dateLabel=(date:string)=>date.split('-').reverse().join('/');
async function request<T>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,options),data=await r.json() as T&{error?:string};if(!r.ok)throw Error(data.error||'Não foi possível concluir. Tente novamente.');return data;}
function downloadCSV(filename:string,rows:(string|number)[][]){const escape=(value:string|number)=>'"'+String(typeof value==='string'&&/^[=+@\-\t\r]/.test(value)?"'"+value:value).replaceAll('"','""')+'"';const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(escape).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const decimal=(cents:number)=>(cents/100).toFixed(2).replace('.',',');
export default function Operations({mode,products,loading,error,reload}:{mode:'stock'|'sales';products:Product[];loading:boolean;error:string;reload:()=>Promise<void>}){
 const [filters,setFilters]=useState({...emptyProductFilters});
 const filteredProducts=filterProducts(products,filters);
 const [start,setStart]=useState(()=>today().slice(0,7)+'-01'),[end,setEnd]=useState(today),[period,setPeriod]=useState(()=>({start:today().slice(0,7)+'-01',end:today()})),[sales,setSales]=useState<Sale[]>([]),[salesLoading,setSalesLoading]=useState(false),[salesError,setSalesError]=useState(''),[revision,setRevision]=useState(0);
 const [stockProduct,setStockProduct]=useState<Product|null>(null),[stock,setStock]=useState(0),[minimum,setMinimum]=useState(3),[busy,setBusy]=useState(false);
 const [saleOpen,setSaleOpen]=useState(false),[saleId,setSaleId]=useState(''),[productId,setProductId]=useState(''),[quantity,setQuantity]=useState(1),[unitPrice,setUnitPrice]=useState(0),[soldOn,setSoldOn]=useState(today),[cancelSale,setCancelSale]=useState<Sale|null>(null);
 const selected=products.find(p=>p.id===productId),summary=summarize(sales),units=products.reduce((s,p)=>s+p.stock,0),low=products.filter(p=>p.stock<=p.stock_min).length,stockCost=products.reduce((s,p)=>s+p.stock*(p.purchase+p.freight/p.quantity),0);
 useEffect(()=>{if(mode!=='sales')return;const controller=new AbortController();setSalesLoading(true);setSalesError('');request<{sales:Sale[]}>(`/api/sales?start=${period.start}&end=${period.end}`,{signal:controller.signal}).then(d=>{setSales(d.sales);}).catch(e=>{if(!controller.signal.aborted)setSalesError(e.message);}).finally(()=>{if(!controller.signal.aborted)setSalesLoading(false);});return()=>controller.abort();},[mode,period,revision]);
 function openStock(p:Product){setStockProduct(p);setStock(p.stock);setMinimum(p.stock_min);}
 async function saveStock(e:FormEvent){e.preventDefault();if(!stockProduct||busy)return;setBusy(true);try{await request('/api/stock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:stockProduct.id,stock,stockMin:minimum,expected:stockProduct.stock})});setStockProduct(null);await reload();toast.success('Estoque atualizado.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 function newSale(){setSaleId(crypto.randomUUID());setProductId('');setQuantity(1);setUnitPrice(0);setSoldOn(today());setSaleOpen(true);}
 async function saveSale(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);try{await request('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:saleId,productId,quantity,unitPrice,soldOn})});setSaleOpen(false);setRevision(r=>r+1);await reload();toast.success('Venda registrada e estoque atualizado.'+(soldOn<period.start||soldOn>period.end?' A venda está fora do período exibido.':''));}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function cancel(){if(!cancelSale||busy)return;setBusy(true);try{await request('/api/sales',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:cancelSale.id})});setCancelSale(null);setRevision(r=>r+1);await reload();toast.success('Venda cancelada. Peças devolvidas ao estoque.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 function exportStock(){downloadCSV(`estoque-${today()}.csv`,[['Produto','SKU','Categoria','Saldo atual','Estoque mínimo','Status','Custo de aquisição unitário (R$)','Valor em estoque (R$)'],...filteredProducts.map(p=>[p.name,p.sku??'',p.category,p.stock,p.stock_min,p.stock===0?'Sem estoque':p.stock<=p.stock_min?'Estoque baixo':'Disponível',(p.purchase+p.freight/p.quantity).toFixed(2).replace('.',','),(p.stock*(p.purchase+p.freight/p.quantity)).toFixed(2).replace('.',',')])]);}
 function exportSales(){downloadCSV(`vendas-${period.start}-a-${period.end}.csv`,[['Data','Produto','Categoria','Quantidade','Preço unitário (R$)','Total (R$)','Custos (R$)','Taxas e impostos (R$)','Lucro estimado (R$)','Situação'],...sales.map(s=>[dateLabel(s.sold_on),s.product_name,s.category,s.quantity,decimal(s.unit_price),decimal(s.total),decimal(s.cost_total),decimal(s.fee_total),decimal(s.total-s.cost_total-s.fee_total),s.cancelled?'Cancelada — fora dos totais':'Confirmada']),[],['TOTAIS CONFIRMADOS','','',summary.units,'',decimal(summary.revenue),decimal(summary.cost),decimal(summary.fees),decimal(summary.profit),'']]);}
 return <div className="operations"><div className="products-heading"><div><h2>{mode==='stock'?'Estoque sob controle.':'Suas vendas, em números.'}</h2><p>{mode==='stock'?'Informe o saldo real de cada peça. As vendas atualizam as quantidades automaticamente.':'Registre as vendas e acompanhe os resultados por período.'}</p></div><div className="action-group">{mode==='sales'&&<button className="primary" onClick={newSale} disabled={loading||!!error||!products.length}><Plus size={17}/> Registrar venda</button>}<button className="outline" onClick={()=>{if(mode==='stock')reload();else setRevision(r=>r+1);}} aria-label="Atualizar dados"><RefreshCw size={16}/></button></div></div>
 {mode==='stock'?<>{loading?<p className="loading">Carregando estoque…</p>:error?<div className="error-box">{error}<button className="outline" onClick={reload}>Tentar novamente</button></div>:<><div className="metrics"><Metric label="Peças disponíveis" value={String(units)} icon={<Package size={20}/>}/><Metric label="Valor em estoque" value={money(stockCost)} detail="Compra + frete de aquisição"/><Metric label="Produtos para repor" value={String(low)} detail="Saldo no mínimo ou abaixo"/></div><ProductFilters value={filters} onChange={setFilters} count={filteredProducts.length} total={products.length}/><section className="panel report-panel"><div className="section-heading"><h2>Relatório de estoque</h2><button className="outline" onClick={exportStock} disabled={!filteredProducts.length}><Download size={16}/> Baixar CSV</button></div><p className="report-note">Produtos existentes começam com saldo zero. O campo “Peças no pedido” da calculadora serve apenas para ratear o frete. O CSV contém os produtos filtrados; os indicadores acima mostram o estoque total.</p>{!products.length?<Empty><EmptyHeader><EmptyTitle>Nenhuma peça cadastrada</EmptyTitle><EmptyDescription>Cadastre seus produtos na calculadora e depois informe as quantidades aqui.</EmptyDescription></EmptyHeader></Empty>:filteredProducts.length===0?<Empty><EmptyHeader><EmptyTitle>Nenhuma peça encontrada</EmptyTitle><EmptyDescription>Altere a busca ou limpe os filtros para ver mais produtos.</EmptyDescription></EmptyHeader></Empty>:<Table><TableHeader><TableRow><TableHead>Produto</TableHead><TableHead>Saldo</TableHead><TableHead>Mínimo</TableHead><TableHead>Situação</TableHead><TableHead>Valor em estoque</TableHead><TableHead>Ajuste</TableHead></TableRow></TableHeader><TableBody>{filteredProducts.map(p=><TableRow key={p.id}><TableCell><div className="table-product">{p.photo&&<img src={p.photo} alt=""/>}<div><strong>{p.name}</strong>{p.sku&&<small className="product-sku">SKU: {p.sku}</small>}<small>{p.category}</small></div></div></TableCell><TableCell><b>{p.stock}</b> un.</TableCell><TableCell>{p.stock_min} un.</TableCell><TableCell><span className={'inventory-status '+(p.stock<=p.stock_min?'low':'')}>{p.stock===0?'Sem estoque':p.stock<=p.stock_min?'Estoque baixo':'Disponível'}</span></TableCell><TableCell>{money(p.stock*(p.purchase+p.freight/p.quantity))}</TableCell><TableCell><button className="outline" onClick={()=>openStock(p)} aria-label={`Ajustar estoque de ${p.name}`}><Pencil size={14}/> Ajustar</button></TableCell></TableRow>)}</TableBody></Table>}</section></> }</>:<>
 {error&&<div className="error-box" role="alert">{error}<button className="outline" onClick={reload}>Recarregar produtos</button></div>}{!loading&&!error&&!products.length&&<p className="report-note">Cadastre uma peça e informe seu saldo na aba Estoque para começar a registrar vendas.</p>}
 <form className="period-filter panel" onSubmit={e=>{e.preventDefault();if(start>end){toast.error('A data inicial deve ser anterior à final.');return;}setPeriod({start,end});}}><label className="field">Data inicial<input className="plain-input" type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field">Data final<input className="plain-input" type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="primary">Aplicar período</button><button className="outline" type="button" onClick={exportSales} disabled={salesLoading||!!salesError||!sales.length}><Download size={16}/> Baixar CSV</button></form>
 {salesLoading?<p className="loading" role="status">Carregando relatório…</p>:salesError?<div className="error-box" role="alert">{salesError}<button className="outline" onClick={()=>setRevision(r=>r+1)}>Tentar novamente</button></div>:<><p className="report-period">De {dateLabel(period.start)} a {dateLabel(period.end)} · Vendas canceladas não entram nos totais.</p><div className="metrics sales-metrics"><Metric label="Faturamento" value={money(summary.revenue/100)} icon={<ShoppingBag size={20}/>}/><Metric label="Lucro estimado" value={money(summary.profit/100)} detail="Após custos e taxas informados"/><Metric label="Peças vendidas" value={String(summary.units)}/><Metric label="Registros de venda" value={String(summary.records)}/></div><section className="panel report-panel"><div className="section-heading"><h2>Vendas no período</h2></div><p className="report-note">Os custos e as taxas ficam registrados no momento da venda. Alterações futuras no produto não mudam este histórico.</p>{!sales.length?<Empty><EmptyHeader><EmptyTitle>Nenhuma venda neste período</EmptyTitle><EmptyDescription>Registre uma venda ou escolha outro intervalo de datas.</EmptyDescription></EmptyHeader></Empty>:<Table><TableHeader><TableRow><TableHead>Data / produto</TableHead><TableHead>Quantidade</TableHead><TableHead>Total</TableHead><TableHead>Lucro estimado</TableHead><TableHead>Situação</TableHead><TableHead>Ação</TableHead></TableRow></TableHeader><TableBody>{sales.map(s=><TableRow key={s.id} className={s.cancelled?'cancelled-row':''}><TableCell><div className="table-product"><div><strong>{s.product_name}</strong><small>{dateLabel(s.sold_on)} · {money(s.unit_price/100)} por peça</small></div></div></TableCell><TableCell>{s.quantity} un.</TableCell><TableCell>{money(s.total/100)}</TableCell><TableCell className={s.total-s.cost_total-s.fee_total<0?'warning-text':''}>{money((s.total-s.cost_total-s.fee_total)/100)}</TableCell><TableCell><span className={'inventory-status '+(s.cancelled?'neutral':'')}>{s.cancelled?'Cancelada':'Confirmada'}</span></TableCell><TableCell>{!s.cancelled&&<button className="outline" onClick={()=>setCancelSale(s)} aria-label={`Cancelar venda de ${s.product_name}`}><RotateCcw size={14}/> Cancelar</button>}</TableCell></TableRow>)}</TableBody></Table>}</section></>}
 </>}
 <Dialog open={!!stockProduct} onOpenChange={open=>{if(!open&&!busy)setStockProduct(null);}}><DialogContent><DialogHeader><DialogTitle>Ajustar estoque</DialogTitle><DialogDescription>{stockProduct?.name} · Saldo atual: {stockProduct?.stock} unidades. Informe a quantidade total disponível após a reposição ou conferência.</DialogDescription></DialogHeader><form onSubmit={saveStock} className="operations-form"><label className="field">Novo saldo total<input className="plain-input" type="number" min="0" max="1000000" step="1" required value={stock} onChange={e=>setStock(Number(e.target.value))}/></label><label className="field">Estoque mínimo<input className="plain-input" type="number" min="0" max="1000000" step="1" required value={minimum} onChange={e=>setMinimum(Number(e.target.value))}/><small>O alerta aparece quando o saldo chega a este valor.</small></label><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar estoque'}</button></form></DialogContent></Dialog>
 <Dialog open={saleOpen} onOpenChange={open=>{if(!busy)setSaleOpen(open);}}><DialogContent><DialogHeader><DialogTitle>Registrar venda</DialogTitle><DialogDescription>Registre uma peça ou várias unidades do mesmo produto. A quantidade será descontada do estoque.</DialogDescription></DialogHeader><form onSubmit={saveSale} className="operations-form"><div className="field"><label htmlFor="sale-product">Produto</label><Select value={productId} onValueChange={v=>{setProductId(v);const p=products.find(p=>p.id===v);if(p)setUnitPrice(calculate(p).price);}}><SelectTrigger id="sale-product" className="category-select"><SelectValue placeholder="Selecione uma peça"/></SelectTrigger><SelectContent>{products.map(p=><SelectItem key={p.id} value={p.id} disabled={p.stock===0}>{p.name}{p.sku?` · SKU: ${p.sku}`:''} · {p.stock} un.</SelectItem>)}</SelectContent></Select>{selected&&<small>Disponível: {selected.stock} unidades.</small>}{products.length>0&&products.every(p=>p.stock===0)&&<small>Informe as quantidades na aba Estoque antes de vender.</small>}</div><div className="fields-grid"><label className="field">Quantidade<input className="plain-input" type="number" min="1" max={selected?.stock||1} step="1" required value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label className="field">Preço por peça (R$)<input className="plain-input" type="number" min="0.01" max="1000000" step="0.01" required value={unitPrice||''} onChange={e=>setUnitPrice(Number(e.target.value))}/></label></div><label className="field">Data da venda<input className="plain-input" type="date" min="2000-01-01" max={today()} value={soldOn} onChange={e=>setSoldOn(e.target.value)} required/></label><div className="cost-total"><span>Total da venda</span><strong>{money(Math.round(unitPrice*100)*quantity/100)}</strong></div><button className="primary" disabled={busy||!selected||quantity>selected.stock}>{busy?'Registrando…':'Confirmar venda'}</button></form></DialogContent></Dialog>
 <AlertDialog open={!!cancelSale} onOpenChange={open=>{if(!open&&!busy)setCancelSale(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Cancelar esta venda?</AlertDialogTitle><AlertDialogDescription>{cancelSale?.product_name}: {cancelSale?.quantity} unidades voltarão ao estoque. A venda ficará marcada como cancelada e sairá dos totais.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Manter venda</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();cancel();}}>{busy?'Cancelando…':'Cancelar e devolver ao estoque'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function Metric({label,value,detail,icon}:{label:string;value:string;detail?:string;icon?:React.ReactNode}){return <div className="metric"><div><span>{label}</span>{icon}</div><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
